### ISSUE TITLE
Diskstore should flush memory as SSTable and read from both.

### ISSUE THREAD

**Issue by scv119** [scv119/pydynamo#14]
- Diskstore should flush memory table as sstable when the size of memory table exceeds a configurable threshold
- The flush shouldn't block ongoing read and write; thus you should do flush in another thread
- Also it means you need to create at least two memtable; i.e. when flushing one memtable, a new memtable is created for accepting ongoing write.
- Once the memory table is flushed; Diskstore should server the read traffic from both memtable and sstables

**Comment by fanmengying** [comment]
as we discussed, the task shall proceed into four steps:
1. complete flush which blocks the write and read action when the mem_table is being flushed.
2. complete read function including reading from mem_table and multiple sstable files
3. complete multithreaded non-blocking flush 
4. complete restart
